### ISSUE TITLE
header with wrong colspan and inner table inheriting outer table header 

### ISSUE THREAD

**Issue by shaunlebron** [yogthos/clj-pdf#38]
I'm seeing two problems in the table rendering from the full example pdf in readme.  The outer table header should have a colspan of 3, and the inner table header shouldn't be there.

I suppose these are quirks are with iText? Couldn't find errors in the code.

```clj
   [:table {:header [{:color [100 100 100]} "FOO"] :cellSpacing 20}
    ["foo"
     [:cell
      [:phrase
       {:style "italic" :size 18 :family "halvetica" :color [200 55 221]}
       "Hello Clojure!"]]
     "baz"]
    ["foo1" [:cell {:color [100 10 200]} "bar1"] "baz1"]
    ["foo2" "bar2" [:cell ["table" ["Inner table Col1" "Inner table Col2" "Inner table Col3"]]]]]

```

![table](https://cloud.githubusercontent.com/assets/116838/5769661/3ae96be0-9ce4-11e4-95ea-2d2323e5feca.png)

**Comment by yogthos** [comment]
Yeah, from what I can tell iText does get into weird behaviors with tables. I haven't found a workaround for every case unfortunately.

**Comment by shaunlebron** [comment]
Would you say that using `pdf-table` produces more predictable results?

**Comment by yogthos** [comment]
I believe so, they each have their quirks I found and it's a bit of a mixed bag.

**Comment by shaunlebron** [comment]
okay, thanks yogthos

**Comment by shaunlebron** [comment]
oh, btw, the inner table is inheriting the outer table's header because of how the meta map is being passed down through nested `make-section` calls.  I'm a little wary to mess with this since since I don't know which attributes you are intending to be inheritable.  CSS only has a subset of inherting attributes like font styling ([full list](http://www.w3.org/TR/CSS21/propidx.html))

**Comment by yogthos** [comment]
Ah I see, so I guess workaround for now is to specify a `nil` header for the inner table:

```clojure
[:table {:header [{:color [100 100 100]} "FOO"] :cellSpacing 20}
    ["foo"
     [:cell
      [:phrase
       {:style "italic" :size 18 :family "halvetica" :color [200 55 221]}
       "Hello Clojure!"]]
     "baz"]
    ["foo1" [:cell {:color [100 10 200]} "bar1"] "baz1"]
    ["foo2" "bar2" [:cell ["table" {:header nil} ["Inner table Col1" "Inner table Col2" "Inner table Col3"]]]]]
```
It would probably make sense to strip node specific meta, like the heading text before passing it on.

**Comment by yogthos** [comment]
I don't have strong feelings about which style elements should be propagated, so I'm open to suggestions on this one. :)

**Comment by yogthos** [comment]
Turns out there was another problem here with `:color` being used for text color for other elements. I renamed `:color` to `:background-color` for tables and now I dissoc the table specific attributes:

```clojure
(dissoc meta :header :align :offset :num-cols :width :widths)
```

I believe table is the only element that's affected by this, as other types of elements have generic metadata that would make sense to propagate to children. So, `:color` to `:background-color` is a breaking change, but otherwise everything should be working hopefully.

**Comment by shaunlebron** [comment]
Oh, good catch.  I'll be building contract PDFs with pdf-table mainly, so I'll let you know if that experience sways me one way or another on which attributes are passed down.  You'll probably see a PR from me soon to dissoc attributes for pdf-table.

Maybe an attribute blacklist should be dissoc'd at `make-section`; something to think about.

**Comment by yogthos** [comment]
Sounds good, I looked at the pdf-table attributes and nothing jumped out at me as obviously wrong to pass down. I guess the question is whether the child table should inherit stuff like cell spacing, border width, etc.

I can see an argument either way. Since other elements such as paragraphs pass down their style to children, it would probably consistent for tables to style their child tables the same way by default as well.

Making a global set of keys to dissoc and doing it uniformly in `make-section` might work better as well since it's easier to catch there than having to pepper dissocs across different elements. If you want to change that with your pr I'm definitely ok with that.
